before:
  hooks:
    - go mod tidy
    - ./scripts/completions.sh
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -v
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X github.com/j178/leetgo/constants.Version={{.Version}}
      - -X github.com/j178/leetgo/constants.Commit={{.Commit}}
      - -X github.com/j178/leetgo/constants.BuildDate={{.Date}}

archives:
  - format: tar.gz
    rlcp: true
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip
    files:
      - LICENSE
      - README*
      - CHANGELOG*
      - completions/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  use: github
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '(?i)^Minor'
brews:
- tap:
    owner: j178
    name: homebrew-tap
  commit_author:
    name: goreleaserbot
    email: bot@goreleaser.com
  homepage: https://github.com/j178/leetgo
  description: >-
    leetgo is a command line tool for leetcode.com. It can help you to login,
    submit, test, and view your submissions.
  license: MIT
  install: |-
    bin.install "leetgo"
    bash_completion.install "completions/leetgo.bash" => "leetgo"
    zsh_completion.install "completions/leetgo.zsh" => "_leetgo"
    fish_completion.install "completions/leetgo.fish"
  test: |-
    system "#{bin}/leetgo", "-v"

scoop:
    bucket:
      owner: j178
      name: scoop-bucket
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    folder: bucket
    homepage: https://github.com/j178/leetgo
    description: >-
      leetgo is a command line tool for leetcode.com. It can help you to login,
      submit, test, and view your submissions.
    license: MIT

announce:
  # DISCORD_WEBHOOK_ID and DISCORD_WEBHOOK_TOKEN
  discord:
    enabled: true

# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
