before:
  hooks:
    - go mod tidy
    - ./scripts/completions.sh
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -v
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X github.com/j178/leetgo/constants.Version={{.Version}}
      - -X github.com/j178/leetgo/constants.Commit={{.Commit}}
      - -X github.com/j178/leetgo/constants.BuildDate={{.Date}}

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README*
      - CHANGELOG*
      - completions/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  use: github
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '(?i)^Minor'
brews:
  - repository:
      owner: j178
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    homepage: https://github.com/j178/leetgo
    description: >-
      leetgo is a command line tool for leetcode.com. It can help you to login,
      submit, test, and view your submissions.
    license: MIT
    install: |-
      bin.install "leetgo"
      bash_completion.install "completions/leetgo.bash" => "leetgo"
      zsh_completion.install "completions/leetgo.zsh" => "_leetgo"
      fish_completion.install "completions/leetgo.fish"
    test: |-
      system "#{bin}/leetgo", "-v"

scoops:
  - repository:
      owner: j178
      name: scoop-bucket
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    folder: bucket
    homepage: https://github.com/j178/leetgo
    description: >-
      leetgo is a command line tool for leetcode.com. It can help you to login,
      submit, test, and view your submissions.
    license: MIT

aurs:
  - homepage: https://github.com/j178/leetgo
    description: >-
      leetgo is a command line tool for leetcode.com. It can help you to login,
      submit, test, and view your submissions.
    license: MIT
    maintainers:
      - "j178 <10510431+j178@users.noreply.github.com>"
    private_key: "{{ .Env.AUR_PRIVATE_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/leetgo-bin.git"
    package: |-
      # bin
      install -Dm755 "./leetgo" "${pkgdir}/usr/bin/leetgo"

      # license
      install -Dm644 "./LICENSE.md" "${pkgdir}/usr/share/licenses/leetgo/LICENSE"

      # completions
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
      mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
      install -Dm644 "./completions/leetgo.bash" "${pkgdir}/usr/share/bash-completion/completions/leetgo"
      install -Dm644 "./completions/leetgo.zsh" "${pkgdir}/usr/share/zsh/site-functions/_leetgo"
      install -Dm644 "./completions/leetgo.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/leetgo.fish"

announce:
  # DISCORD_WEBHOOK_ID and DISCORD_WEBHOOK_TOKEN
  discord:
    enabled: true

# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
