name: Bug report
description: Create a report to help us improve
title: "[Bug] "
body:
  - type: checkboxes
    id: ensure
    attributes:
      label: Verification steps
      description: "
在提交之前，请确认
Please verify that you've followed these steps
"
      options:
        - label: "
我已经在 [Issue Tracker](https://github.com/j178/leetgo/issues) 和 [Discussion](https://github.com/j178/leetgo/discussions) 中找过我要提出的问题
I have searched on the [issue tracker](https://github.com/j178/leetgo/issues) and [Discussion](https://github.com/j178/leetgo/discussions) for a related issue.
"
          required: true
  - type: textarea
    attributes:
      render: shell
      label: "leetgo config"
      description: "
在下方附上 `leetgo debug` 的输出
Paste the output of `leetgo debug` below
"
    validations:
      required: true
  - type: textarea
    attributes:
      render: shell
      label: Debug log
      description: "
请设置环境变量 `DEBUG=1`(PowerShell: `$env:DEBUG=1`, CMD: `set DEBUG=1`, Others: `export DEBUG=1`) 后再运行有问题的 leetgo 命令，并在下方附上 `leetgo` 的输出
Set environment variable `DEBUG=1`(PowerShell: `$env:DEBUG=1`, CMD: `set DEBUG=1`, Others: `export DEBUG=1`) and run the leetgo command that has the issue, and paste the output of `leetgo` below
"
  - type: textarea
    attributes:
      label: Description
    validations:
      required: true
