package lang

import (
	"fmt"
	"path/filepath"

	"github.com/j178/leetgo/leetcode"
)

const (
	testutilsModPath = "github.com/j178/leetgo/testutils/go"
	testFileTemplate = `
// Code generated by https://github.com/j178/leetgo

package main

import (
    "testing"

    . "%s"
)

var testcases = ` + "`" + `
%s
` + "`" + `

func Test_%s(t *testing.T) {
    targetCaseNum := 0
    // targetCaseNum := -1
    if err := %s(t, %s, testcases, targetCaseNum); err != nil {
        t.Fatal(err)
    }
}
`
)

type golang struct {
	baseLang
}

func addNamedReturn(code string, q *leetcode.QuestionData) string {
	return code
}

func changeReceiverName(code string, q *leetcode.QuestionData) string {
	return code
}

func (g golang) CheckLibrary() bool {
	// 执行 go list -m json 查看是否有 github.com/j178/leetgo/testutils/go 的依赖
	// go list -m -json github.com/j178/leetgo/testutils/go => not a known dependency
	return true
}

func (g golang) GenerateLibrary() error {
	// remove go.mod
	// 执行 go mod init & go get
	return nil
}

func (g golang) RunTest(q *leetcode.QuestionData) error {
	// run go test
	return nil
}

func (g golang) generateTest(q *leetcode.QuestionData, testcases string) string {
	var funcName, testFuncName string
	if q.MetaData.SystemDesign {
		funcName = "Constructor"
		testFuncName = "RunClassTestsWithString"
	} else {
		funcName = q.MetaData.Name
		testFuncName = "RunTestsWithString"
	}
	content := fmt.Sprintf(testFileTemplate, testutilsModPath, testcases, funcName, testFuncName, funcName)
	return content
}

func (g golang) Generate(q *leetcode.QuestionData) ([]FileOutput, error) {
	comment := g.generateComments(q)
	code := g.generateCode(
		q,
		addCodeMark(g.lineComment),
		removeComments,
		addNamedReturn,
		changeReceiverName,
		prepend("package main\n\n"),
	)
	codeContent := comment + "\n" + code + "\n"

	testcaseStr := g.generateTestCases(q)
	testContent := g.generateTest(q, testcaseStr)

	filenameTmpl := getFilenameTemplate(g)
	baseFilename, err := q.GetFormattedFilename(g.slug, filenameTmpl)
	if err != nil {
		return nil, err
	}
	codeFile := filepath.Join(baseFilename, "solution.go")
	testFile := filepath.Join(baseFilename, "solution_test.go")

	files := []FileOutput{
		{
			Path:    codeFile,
			Content: codeContent,
		},
		{
			Path:    testFile,
			Content: testContent,
		},
	}

	return files, nil
}
